name: typewell_gr_alignment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - kaggle
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - pyarrow
  - pyyaml
  - requests
  - pytest
  - tqdm
  - rich
  - matplotlib
  - seaborn
  - ipykernel
  - xgboost
  - scipy
  - pytorch
  - pytorch-cuda=12.1
  - pyproj
  - pip:
      - openai>=1.40
      - lancedb
      - kagglehub>=0.3
